# https://www.pulumi.com/docs/iac/guides/continuous-delivery/pulumi-kubernetes-operator/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/pulumi/pulumi-kubernetes-operator/v2.3.0/deploy/quickstart/install.yaml

# May fail with 403 error, seems to be random
# response status code 403: denied: requested access to the resource is denied : unable to run: 'helm pull --untar --untardir <path to cached source>/apps/pulumi/aws/envs/dev/charts/pulumi-kubernetes-operator-2.3.0 oci://ghcr.io/pulumi/helm-charts/pulumi-kubernetes-operator/pulumi-kubernetes-operator --version 2.3.0'
#
# helmCharts:
#   - name: pulumi-kubernetes-operator
#     repo: oci://ghcr.io/pulumi/helm-charts/pulumi-kubernetes-operator
#     version: 2.3.0
#     releaseName: pulumi
#     namespace: pulumi
#     # valuesFile: values.yaml
