apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: v2.0.0
    releaseName: external-secrets
    namespace: external-secrets
    valuesInline:
      serviceAccount:
        # Must match any external identity associations
        name: external-secrets-sa
