apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datashield

resources:
  - datashield-external-secrets.yaml
  - opal-resource-db-external-secret.yaml
  - postgres.yaml
  - opal-gateway-route.yaml
