apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datashield

resources:
  - certificate.yaml
  - datashield-external-secrets.yaml
  - opal-resource-db-external-secret.yaml
  - postgres.yaml
  - storage-class.yaml
  - opal-gateway-route.yaml
  - rbac.yaml
