apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - netpol_singleuser.yaml
  - netpol_singleuser_world.yaml
  - network_policy.yaml
  - patch-rolebinding.yaml
  - jupyterhub-external-secret.yaml
  - gateway-route.yaml
  - backend-config.yaml
  - auth-proxy-nginx.yaml

patches:
  - path: patch-hub-rolebinding.yaml
    target:
      kind: Job
      name: patch-hub-rolebinding
