apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cr8tor
resources:
- certificate.yaml
- cr8tor-configmap.yaml
- cr8tor-external-secret.yaml
- networkpolicy.yaml
- opal-external-secret.yaml
- storage-class.yaml
- admin-external-secret.yaml

# cr8tor-operator
- https://github.com/karectl-crates/cr8tor//manifests/cr8tor-operator?ref=feature/at-guacamole-iam
- cr8tor-operator-realm-config.yaml
