apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cr8tor
resources:
- certificate.yaml
- cr8tor-configmap.yaml
- cr8tor-external-secret.yaml
- networkpolicy.yaml
- admin-external-secret.yaml
- gateway-route.yaml
- cr8tor-operator-realm-config.yaml
