apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: opal
    repo: https://obiba.github.io/helm-charts
    version: 1.1.0
    releaseName: opal
    namespace: datashield
    valuesFile: values.yaml
      
resources:
  - ../../base

patches:
  - path: opal-gateway-route-patch.yaml
    target:
      kind: HTTPRoute
      name: opal-route
