apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

resources:
  - ../../base

# Image patch for dev environment
patches:
  - path: image-patch.yaml
    target:
      kind: Deployment
      name: backend
