apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-rbac.yaml
  - service.yaml
  - external-secret.yaml
  - gateway-route.yaml
  - backend-config.yaml
  - deployment.yaml
