image:
  registry: ghcr.io
  repository: karectl-crates/cr8tor-operator
  tag: "dev-operator"
  pullPolicy: Always

keycloak:
  adminSecretName: "keycloak-admin-credentials"
  realmConfigMapName: "karectl-realm-config"

config:
  logLevel: "DEBUG"

# Storage configuration for dev
storage:
  defaultStorageClass: "rwo-default"
  defaultVdiSize: "2Gi"
  defaultNotebookSize: "2Gi"
  maxVdiSize: "5Gi"
  maxNotebookSize: "2Gi"
  defaultPersist: false
