apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cr8tor-publisher
    repo: https://lsc-sde.github.io/iac-helm-repository/
    version: 0.1.65
    releaseName: cr8tor
    namespace: cr8tor
    valuesFile: values.yaml

resources:
  - ../../base
