apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-secret.yaml
  - dcqm-service-monitor.yaml
  - gateway-route.yaml
  - dashboards/vllm-query-dashboard.yaml
  - dashboards/nvidia-dcgm-dashboard.yaml

helmCharts:
  - name: kube-prometheus-stack
    releaseName: prometheus-community
    version: 80.14.0
    repo: https://prometheus-community.github.io/helm-charts
    namespace: observability
    valuesFile: values.yaml
    includeCRDs: false