apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Prd uses same values as base (same as stg)
helmCharts:
  - name: datashield
    repo: https://lsc-sde.github.io/iac-helm-datashield/
    version: 0.11.0
    releaseName: datashield
    namespace: datashield
    valuesFile: values.yaml

# Prd-specific postgres resources (same as stg)
patches:
  - path: postgres-patch.yaml
    target:
      kind: Cluster
      name: datashield-postgres-cluster
