fullnameOverride: external-dns

serviceAccount:
  create: true
  name: externaldns
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "b1b34079-15b8-4bbe-a09f-0fd7bb720fdc"

podLabels:
  azure.workload.identity/use: "true"

extraVolumes:
  - name: azure-config-file
    secret:
      secretName: external-dns-azure

extraVolumeMounts:
  - name: azure-config-file
    mountPath: /etc/kubernetes
    readOnly: true

provider:
  name: azure-private-dns

policy: sync
txtOwnerId: externaldns

domainFilters:
  - karectl.org